### GET request with a header
GET http://127.0.0.1:8081/api/order
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODQ2NjgxNDcsImV4cCI6MTY4NDY3MTc0Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibWFyaW9vLnJhYkBnbWFpbC5jb20ifQ.lD54yQs_kJES7W4PhxLD0nWIWGFL3nydtqFMNeBIst0Czbv1MTj-xlXSuUEGB8F4qFvNuCeuNDK19WDIZqVpE4l3FDsizyPerbgqDToGD1K0BeV8RakGDmEuXPzcoNhr4YrS8wqlt4KtKLyTgDPXPGyR9j85i8JVgLnD2G0ljdtwvLiAGeNallH8RP67tHUAXQP4b9SkGyR5JSd78JzC3RxdqUOm_uBcHyOKwm2QTUJryHHPg_eIDw063SfAThEuhgGfoM38hKgeudfZwTNVIn28sB6-UbMdqqj10QHrTO3idG_ACioBGomMxgBT_JeayKBedlGUmmpTxjtFLUT5zA


### GET request with a header
GET http://127.0.0.1:8081/api/order
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODQ2NjkyMTEsImV4cCI6MTY4NDY3MjgxMSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoicGVhLmxpbGlhbkBnbWFpbC5jb20ifQ.RdfR_FVgvoYhuB_o2w3uYkEMl1jgkM5u2ENVbpZ4GNCuXvTc9MrOAgCIp0dvVPL_Baa7tWKo-qFdEjhwATry119K-l5jADHmgXuee1zIrFaqRj9m75KlsDqIMT3d8k1xEmyKSCnvwsGzUbSf_XWsj0gLYcBfF6laIV_FBsUlvfzTdrQ86wW9ltV3rV8mPFeceTvtdaYfjrWv9TldISNNMH_mz9kB8tTbJQqM8o_2ZjOH-4-xH1TrgFimobhxzISwPiaU9CGt5KmKJmi-dHJw5i_UgVdiq7jpSFogYIUhdd2mkAyK6Cd7IPE9KAyBaw0AT_j7nZ9uu70LBxbHFjHVcg
